### ISSUE TITLE
Error: Calculated Fee is below Minimum

### ISSUE THREAD

**Issue by whattocode** [wharfkit/transact-plugin-autocorrect#4]
![Screenshot 2024-06-07 at 12 19 31 AM](https://github.com/wharfkit/transact-plugin-autocorrect/assets/50191294/56a16753-3ca3-465a-b50f-830bfc742bff)
<img width="403" alt="Screenshot 2024-06-07 at 12 33 44 AM" src="https://github.com/wharfkit/transact-plugin-autocorrect/assets/50191294/6669625d-95e7-4927-b9c6-f2c7b4818a7a">

```
//new instance
 new SessionKit(
        {//args: SessionKitArgs
        },
        {
            transactPlugins: [
                new TransactPluginAutoCorrect(),
            ]
        });
```

````
// Could you make the cost bigger than the minimum fee and ensure that the transaction doesn't fail? 
// Thanks...
````

**Comment by aaroncox** [comment]
Which network is this happening on?

And can you confirm you're on the latest versions of all the plugins and dependencies? I know we've been making updates recently, and want to make sure you're running the latest code.

**Comment by whattocode** [comment]
> Which network is this happening on?
> 
> And can you confirm you're on the latest versions of all the plugins and dependencies? I know we've been making updates recently, and want to make sure you're running the latest code.

The issue is occurring on the Jungle Testnet.

I have updated to the latest versions of all the plugins and dependencies, but the issue still persists.

**Comment by whattocode** [comment]
It seems that the error occurs when the 'Accept Transaction Fee' is less than 0.001 EOS (Cost of CPU/NET), but I'm not 100% sure.

**Comment by aaroncox** [comment]
This could also be Jungle 4 related, I've experienced some really weird things when trying to use powerup there. The code seems to work very well now on both EOS and WAX, but on Jungle, you end up with errors like this alongside wild fluctuations in CPU/NET from staked resources.

**Comment by whattocode** [comment]
Thanks for the info on Jungle 4. I appreciate your help with this issue.

**Comment by aaroncox** [comment]
Not a problem! 

At this point I wish I knew exactly what it is that's causing this weirdness on Jungle 4. It could be a lack of real activity causing parameters to fluctuate wildly, or maybe it was misconfigured when it was launched - I'm not sure. I know I've mentioned it in the Jungle discussion channels on Telegram in the past.
