### ISSUE TITLE
Doesn't work when account is low on both CPU/NET and RAM

### ISSUE THREAD

**Issue by jeisses** [wharfkit/transact-plugin-autocorrect#5]
When an account is low on both CPU/NET and RAM, the plugin gives the following error while trying to compose the transaction:

```
Error: Error: Too many iterations. Please report this bug if you see it.
```

**Expected behaviour**
The plugin should compose a transaction with both `powerup` and `buyram` actions in there

**What goes wrong**
To me it looks like the following deadlock is happening: 

- The plugin calls `compute_transaction` on the RPC, which says RAM is low. 
- Then it calls `compute_transaction` for the `buyram`, which says CPU is low. 
- Then it calls it on the `powerup`, which says RAM is low. 

The way it resolves issues recursively doesn't work as it needs both a `buyram` and `powerup` at the same time

**Comment by aaroncox** [comment]
Alright, version 1.3.0 of the plugin should now detect when an account doesn't have the RAM required to powerup - and then make that RAM purchase to allow the transaction to succeed.

I tested it on one of our test accounts and it seems to succeed - but if you find any more edge cases let us know!

**Comment by co-ninja** [comment]
Hi, it don't work again. I'm using latest version, 
`
    "@wharfkit/antelope": "^1.0.12",
    "@wharfkit/session": "^1.4.0",
    "@wharfkit/transact-plugin-autocorrect": "^1.3.1",
       "@wharfkit/wallet-plugin-anchor": "^1.4.0"
       
       
       new SessionKit(
        {
            appName: APP.name,
            chains: [{
                id: "73e4385a2708e6d7048834fbc1079f2fabb17b3c125b146af438971e90716c4d",
                url: "http://jungle4.greymass.com",
            }],
            ui: new WebRenderer(),
            walletPlugins: [
                new WalletPluginAnchor(),
            ],
        },
        {
            transactPlugins: [
                new TransactPluginAutoCorrect(),
            ]
        });
    
    `

![Screenshot 2024-09-30 at 4 17 01 PM](https://github.com/user-attachments/assets/7888e678-3144-4966-85c9-26ad7ebdda0c)
